services:
  dev:
    image: mcr.microsoft.com/devcontainers/typescript-node:24-bookworm
    networks:
      - interconnect
    tty: true
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock
      # Use SSL server certificate
      - ~/.vscode/ssl:/etc/ssl/local:ro
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../../:/workspaces:cached

networks:
  interconnect:
    driver: bridge
